---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryapp-canary
  namespace: prod
  labels:
    app: queryapp
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queryapp
      version: canary
  template:
    metadata:
      labels:
        app: queryapp
        version: canary
    spec:
      hostname: queryapp
      containers:
      - name: queryapp
        image: eu.gcr.io/$PROJECT_ID/queryapp:$SHORT_SHA
        ports:
        - containerPort: 5003
        env:
        - name: CONFIG_API_URL
          valueFrom:
            configMapKeyRef:
              name: queryapp-env-vars
              key: config_api_url
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: queryapp-canary
  labels:
    app: queryapp
    version: canary
  namespace: prod
spec:
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: queryapp
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: queryapp
  namespace: prod
spec:
  host: queryapp-main
  subsets:
  - name: main
    labels:
      version: main
  - name: canary
    labels:
      version: canary
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: queryapp
  namespace: prod
spec:
  hosts:
  - queryapp.prod.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: queryapp-main.prod.svc.cluster.local
        subset: canary
        port:
          number: 5003
      weight: 10
    - destination:
        host: queryapp-main.prod.svc.cluster.local
        subset: main
        port:
          number: 5003
      weight: 90
